Increase the package version for requests:
* requests 2.21.0 use lower version of urllib3 and this caused a conflict

error: urllib3 1.25.3 is installed but urllib3<1.25,>=1.21.1 is required by {'requests'}

Signed-off-by: Lander Usategui <lander.usategui@gmail.com>